name: First Action demo
on: workflow_dispatch
jobs: 
  fisrt-job: 
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello From github action!"

      - name: Bye greeting
        run: echo "Good bye !"

      - name: printing date time and current user
        run:  | 
          echo "Current Date and Time:" $(date)
          echo "Current User: $(whoami)"
      
